language: minimal

git:
  depth: false

before_install:
  - make version

install:
  - make env
  - source env/conda/bin/activate sphinxcontrib-hdl-diagrams

stages:
    - name:
        - Test
        - Build
        - Deploy

jobs:
    - stage: Tests
      name: "Test :skin: option"
      script:
        - cd tests && python3 -m unittest test.TestSkins

    - stage: Tests
      name: "Test :yosys_script: option"
      script:
        - cd tests && python3 -m unittest test.TestYosysScript

      name: "Test :flatten: option"
      script:
        - cd tests && python3 -m unittest test.TestFlatten

    - stage: Tests
      name: "Test verilog_diagram_yosys config variable"
      script:
        - cd tests && python3 -m unittest test.TestYosysType

    - stage: Tests
      name: "Test nMigen input format"
      script:
        - cd tests && python3 -m unittest test.TestNMigen

    - stage: Tests
      name: "Test RTLIL input format"
      script:
        - cd tests && python3 -m unittest test.TestRTLIL

    - stage: Tests
      name: "Test compatibility package"
      script:
        - cd tests && python3 -m unittest test.TestCompat

    - stage: Build
      name: "Build"
      script:
        - make build

    - stage: Deploy
      name: "PyPI"
      install: null
      before_deploy:
        - sudo ln -sf /usr/bin/python3 /usr/bin/python
      deploy:
        provider: pypi
        username: __token__
        distributions: sdist bdist_wheel
        skip_existing: true
        edge: true # opt in to dpl v2

after_success:
  - bash <(curl -s https://codecov.io/bash)